// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package tutorial

import ()

type Cliente struct {
	IDCliente int32
	Nombre    string
	Apellido  string
	Email     string
	Telefono  string
}
