// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package laborosoDB

import (
	"database/sql"
	"time"
)

type Bill struct {
	IDBill   int32
	IDClient sql.NullInt32
	IDOrder  sql.NullInt32
	Date     sql.NullTime
	Subtotal sql.NullString
	Total    sql.NullString
}

type BillService struct {
	IDService int32
	IDBill    int32
	Quantity  sql.NullInt32
	Cost      sql.NullString
}

type Category struct {
	IDCategory  int32
	Name        string
	Description sql.NullString
}

type CategoryService struct {
	IDService  int32
	IDCategory int32
}

type Client struct {
	IDClient int32
	Passport sql.NullString
	IDCard   sql.NullString
	Name     string
	Lastname string
	Country  string
	Email    string
	Phone    int32
	Dimex    sql.NullString
}

type ClientDirection struct {
	IDDirection int32
	IDClient    sql.NullInt32
	Direction   string
	Province    string
	Canton      string
	District    string
	ZipCode     string
}

type DirectionsWorker struct {
	IDDirection int32
	IDWorker    sql.NullInt32
	Direction   string
	Province    string
	Canton      string
	District    string
	ZipCode     string
}

type Label struct {
	IDLabel     int32
	Name        string
	Description sql.NullString
}

type LabelService struct {
	IDService int32
	IDLabel   int32
}

type Order struct {
	IDOrder   int32
	IDClient  sql.NullInt32
	OrderDate time.Time
	Status    bool
}

type PaymentMethod struct {
	IDPaymentMethod int32
	IDClient        sql.NullInt32
	Name            string
	Number          string
	Expire          time.Time
	Cvv             string
}

type Review struct {
	IDReviews int32
	IDClient  sql.NullInt32
	IDService sql.NullInt32
	Valuation int32
	Comment   string
	Date      time.Time
}

type Schedule struct {
	IDSchedule int32
	IDService  sql.NullInt32
	IDWorker   sql.NullInt32
	WeekDay    string
	StartHour  time.Time
	FinishHour time.Time
}

type Service struct {
	IDService   int32
	Name        string
	Description sql.NullString
	CostNotes   sql.NullString
	Cost        string
}

type Vacation struct {
	IDVacations int32
	IDWorker    sql.NullInt32
	StartDate   time.Time
	FinishDate  time.Time
}

type Worker struct {
	IDWorker            int32
	Name                string
	Lastname            string
	Email               string
	Phone               string
	Passport            sql.NullString
	IDCard              sql.NullString
	Dimex               sql.NullString
	Country             sql.NullString
	ProfessionalProfile string
	Valuation           sql.NullInt32
	Province            string
	Canton              string
	District            sql.NullString
	ZipCode             sql.NullString
	Active              bool
}

type WorkerService struct {
	IDService int32
	IDWorker  int32
}
